apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: headroom-reserver
  namespace: default
  labels:
    app: headroom-reserver
spec:
  selector:
    matchLabels:
      app: headroom-reserver
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: headroom-reserver
    spec:
      priorityClassName: headroom-high
      terminationGracePeriodSeconds: 0
      containers:
        - name: pause
          image: registry.k8s.io/pause:3.9
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"