apiVersion: eks.amazonaws.com/v1
kind: NodeClass
metadata:
  name: soci-snapshotter
spec:
  role: "<<KARPENTER_NODE_IAM_ROLE_NAME>>"
  networkPolicy: DefaultAllow
  networkPolicyEventLogs: Disabled
  snatPolicy: Random
  ephemeralStorage:
    size: "100Gi"
  securityGroupSelectorTerms:
  - tags:
      karpenter.sh/discovery: <<CLUSTER_NAME>>
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: <<CLUSTER_NAME>>
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: soci-snapshotter
spec:
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 5m
  template:
    metadata:
      labels:
        intent: soci-snapshotter
    spec:
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: soci-snapshotter
      requirements:
        - key: eks.amazonaws.com/instance-category
          operator: In
          values:
            - g
        - key: eks.amazonaws.com/instance-generation
          operator: Gt
          values:
            - "4"
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - spot
            - on-demand
      taints:
        - effect: NoSchedule
          key: nvidia.com/gpu
