apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: fast-initialization
spec:
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m
  limits:
    cpu: 1k
    memory: 500Gi
  template:
    metadata:
      labels:
        intent: fast
    spec:
      expireAfter: 168h0m0s
      nodeClassRef:
        group: karpenter.k8s.aws
        name: fast
        kind: EC2NodeClass
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: node.kubernetes.io/instance-type
          operator: In
          values: ["m5.large"] 
      taints:
        - effect: NoSchedule
          key: intent
          value: fast-init
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: slow-initialization
spec:
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m
  limits:
    cpu: 1k
    memory: 500Gi
  template:
    metadata:
      labels:
        intent: slow
    spec:
      expireAfter: 168h0m0s
      nodeClassRef:
        group: karpenter.k8s.aws
        name: slow
        kind: EC2NodeClass
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: node.kubernetes.io/instance-type
          operator: In
          values: ["m5.large"] 
      taints:
        - effect: NoSchedule
          key: intent
          value: slow-init

---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: fast
spec:
  amiFamily: Bottlerocket
  amiSelectorTerms: 
  - alias: bottlerocket@latest
  blockDeviceMappings:
  - deviceName: /dev/xvdc 
    ebs:
      deleteOnTermination: true
      volumeSize: 10Gi
      volumeType: gp3
      volumeInitializationRate: 300
      snapshotID: "snap-06574d40d0a828ee0"
  role: "karpenter-karpenter-blueprints"
  securityGroupSelectorTerms:
  - tags:
      karpenter.sh/discovery: karpenter-blueprints
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: karpenter-blueprints
---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: slow
spec:
  amiFamily: Bottlerocket
  amiSelectorTerms: 
  - alias: bottlerocket@latest
  blockDeviceMappings:
  - deviceName: /dev/xvdc 
    ebs:
      deleteOnTermination: true
      volumeSize: 10Gi
      volumeType: gp3
      volumeInitializationRate: 100
      snapshotID: "snap-06574d40d0a828ee0"
  role: "karpenter-karpenter-blueprints"
  securityGroupSelectorTerms:
  - tags:
      karpenter.sh/discovery: karpenter-blueprints
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: karpenter-blueprints
