apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload
spec:
  replicas: 10
  selector:
    matchLabels:
      app: workload
  template:
    metadata:
      labels:
        app: workload
    spec:
      nodeSelector:
        intent: apps
      containers:
      - name: workload
        image: public.ecr.aws/eks-distro/kubernetes/pause:v1.33.0-eks-1-33-4
        resources:
          requests:
            cpu: 512m
            memory: 512Mi