apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: latest-current-ami-template
spec:
  amiFamily: AL2
  amiSelectorTerms:
  - name: '*1.27*'
    owner: amazon
  role: "<<KARPENTER_NODE_IAM_ROLE_NAME>>"
  securityGroupSelectorTerms:
  - tags:
      karpenter.sh/discovery: <<CLUSTER_NAME>>
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: <<CLUSTER_NAME>>
  tags:
    KubernetesVersion: "1.27"
---
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: latest-current-ami
spec:
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: 168h0m0s
  limits:
    cpu: 100k
    memory: 5000Gi
  template:
    metadata:
      labels:
        intent: latest-current-ami
    spec:
      nodeClassRef:
        name: latest-current-ami-template
      requirements:
      - key: karpenter.k8s.aws/instance-category
        operator: In
        values:
        - c
        - m
        - r
        - i
        - d
      - key: karpenter.k8s.aws/instance-cpu
        operator: In
        values:
        - "4"
        - "8"
        - "16"
        - "32"
        - "48"
        - "64"
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - spot
        - on-demand
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64