apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: custom-ami-template
spec:
  amiFamily: AL2
  amiSelectorTerms:
  - name: '*amazon-eks-node-1.30-*'
  role: "<<KARPENTER_NODE_IAM_ROLE_NAME>>"
  securityGroupSelectorTerms:
  - tags:
      karpenter.sh/discovery: <<CLUSTER_NAME>>
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: <<CLUSTER_NAME>>
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: custom-ami
spec:
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m
  limits:
    cpu: 1k
    memory: 500Gi
  template:
    metadata:
      labels:
        intent: custom-ami
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        name: custom-ami-template
        kind: EC2NodeClass
      requirements:
      - key: karpenter.k8s.aws/instance-hypervisor
        operator: NotIn
        values:
        - ""
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - spot
        - on-demand
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: karpenter.k8s.aws/instance-category
        operator: In
        values:
        - c
        - m
        - r
      - key: karpenter.k8s.aws/instance-generation
        operator: Gt
        values:
        - "2"