apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: multi-ebs
spec:
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m
  limits:
    cpu: 1k
    memory: 500Gi
  template:
    metadata:
      labels:
        intent: multi-ebs
    spec:
      expireAfter: 168h0m0s
      nodeClassRef:
        group: karpenter.k8s.aws
        name: multi-ebs
        kind: EC2NodeClass
      requirements:
      - key: karpenter.k8s.aws/instance-category
        operator: In
        values:
        - c
        - m
        - r
        - i
        - d
      - key: karpenter.k8s.aws/instance-cpu
        operator: In
        values:
        - "4"
        - "8"
        - "16"
        - "32"
        - "48"
        - "64"
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - spot
        - on-demand
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: multi-ebs
spec:
  amiFamily: AL2
  amiSelectorTerms: 
  - alias: al2@latest
  blockDeviceMappings:
  - deviceName: /dev/xvda
    ebs:
      deleteOnTermination: true
      volumeSize: 20Gi
      volumeType: gp3
  - deviceName: /dev/xvdb
    ebs:
      deleteOnTermination: true
      volumeSize: 100Gi
      volumeType: gp3
  role: "karpenter-karpenter-blueprints"
  securityGroupSelectorTerms:
  - tags:
      karpenter.sh/discovery: karpenter-blueprints
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: karpenter-blueprints