apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stateful
spec:
  serviceName: stateful
  replicas: 3
  selector:
    matchLabels:
      app: stateful
  template:
    metadata:
      labels:
        app: stateful
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: stateful
        image: public.ecr.aws/docker/library/centos:centos7.9.2009
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo Writing content every three minutes! Printing a random number: $(( $RANDOM % 1000 + 1 ))>> /data/out.txt; sleep 180; done"]
        volumeMounts:
        - name: persistent-storage
          mountPath: /data
        resources:
          requests:
            cpu: 1
  volumeClaimTemplates:
  - metadata:
      name: persistent-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: storage-gp3
      resources:
        requests:
          storage: 4Gi