apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: migration-nodeclass
spec:
  role: "<<KARPENTER_NODE_IAM_ROLE_NAME>>"
  amiSelectorTerms:
  - alias: al2023@latest
  securityGroupSelectorTerms:
  - tags:
      karpenter.sh/discovery: <<CLUSTER_NAME>>
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: <<CLUSTER_NAME>>
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: reserved-migration
spec:
  template:
    metadata:
      labels:
        intent: apps
    spec:
      nodeClassRef:
        name: migration-nodeclass
        group: karpenter.k8s.aws
        kind: EC2NodeClass
      requirements:
      - key: karpenter.sh/capacity-type
        operator: In
        values: ["on-demand"]
      - key: kubernetes.io/arch
        operator: In
        values: ["amd64", "arm64"]
      - key: topology.kubernetes.io/zone
        operator: In
        values: ["<<AZ>>"]
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m