apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: odcr-nodeclass
spec:
  amiSelectorTerms:
    - alias: al2023@latest
  role: "<<KARPENTER_NODE_IAM_ROLE_NAME>>"
  securityGroupSelectorTerms:
  - tags:
      karpenter.sh/discovery: "<<CLUSTER_NAME>>"
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: "<<CLUSTER_NAME>>"
  capacityReservationSelectorTerms:
  # Select ODCRs by tags - replace with your actual tags
  - tags:
      Environment: production
      Application: web-app
  # Or select specific ODCR by ID - replace with your actual ODCR ID
  # - id: cr-1234567890abcdef0