apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: odcr-nodeclass
spec:
  amiSelectorTerms:
    - alias: al2023@latest
  role: "<<KARPENTER_NODE_IAM_ROLE_NAME>>"
  securityGroupSelectorTerms:
  - tags:
      karpenter.sh/discovery: "<<CLUSTER_NAME>>"
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: "<<CLUSTER_NAME>>"
  capacityReservationSelectorTerms:
  # Select ODCRs by tags - replace with your actual tags
  - tags:
      intent: apps
  # Or select specific ODCR by ID - replace with your actual ODCR ID
  # - id: cr-1234567890abcdef0
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: odcr-priority
spec:
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m
  template:
    metadata:
      labels:
        intent: apps
    spec:
      expireAfter: 168h0m0s
      nodeClassRef:
        group: karpenter.k8s.aws
        name: odcr-nodeclass
        kind: EC2NodeClass
      requirements:
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      # Priority: reserved (ODCR) first, then on-demand fallback
      - key: karpenter.sh/capacity-type
        operator: In
        values: ["reserved", "on-demand"]