apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: odcr-nodeclass
spec:
  amiSelectorTerms:
    - alias: al2023@latest
  role: "karpenter-blueprints"
  securityGroupSelectorTerms:
  - tags:
      karpenter.sh/discovery: karpenter-blueprints
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: karpenter-blueprints
  capacityReservationSelectorTerms:
  - tags:
      intent: apps
      project: karpenter-blueprints
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: odcr-priority
spec:
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m
  template:
    metadata:
      labels:
        intent: apps
        workload-type: odcr
    spec:
      expireAfter: 168h0m0s
      nodeClassRef:
        group: karpenter.k8s.aws
        name: odcr-nodeclass
        kind: EC2NodeClass
      requirements:
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: node.kubernetes.io/instance-type
        operator: In
        values:
        - t3.small
      - key: topology.kubernetes.io/zone
        operator: In
        values:
        - eu-west-2a  # Same AZ as ODCR
      - key: karpenter.sh/capacity-type
        operator: In
        values: ['reserved', 'on-demand']