apiVersion: apps/v1
kind: Deployment
metadata:
  name: savings-workload
spec:
  replicas: 25  # 25 × 1 vCPU = 25 vCPUs (exceeds 20 vCPU limit)
  selector:
    matchLabels:
      app: savings-workload
  template:
    metadata:
      labels:
        app: savings-workload
    spec:

      containers:
      - name: app
        image: public.ecr.aws/eks-distro/kubernetes/pause:v1.33.0-eks-1-33-4
        resources:
          requests:
            cpu: 1000m
            memory: 512Mi