apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: gpu-static
spec:
  replicas: 1
  limits:
    nodes: 2
  template:
    metadata:
      labels:
        capacity-type: gpu-static
        nvidia.com/gpu.present: "true"
        vpc.amazonaws.com/efa.present: "true"
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        name: gpu-static
        kind: EC2NodeClass
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot", "on-demand"]
        - key: node.kubernetes.io/instance-type
          operator: In
          values: ["g6e.8xlarge"]
      expireAfter: Never
      taints:
        - key: nvidia.com/gpu
          effect: NoSchedule
