apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: savings-plans
spec:
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m
  limits:
    cpu: "20" # For example: Limit to launch up to 5 c4.xlarge instances
  template:
    metadata:
      labels:
        intent: apps
    spec:
      expireAfter: 168h0m0s
      nodeClassRef:
        group: karpenter.k8s.aws
        name: default
        kind: EC2NodeClass
      requirements:
      - key: karpenter.k8s.aws/instance-family
        operator: In
        values:
        - c4
        # Alternatively, you can configure fixed instance types
        # - key: "node.kubernetes.io/instance-type"
        #   operator: In
        #   values: ["c4.xlarge"] # 4 vCPUs
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - on-demand
  weight: 100