apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: disruption-budget
spec:
  limits:
    cpu: 100
    memory: 100Gi
  template:
    metadata:
      labels:
        intent: disruption-budget
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        name: disruption-budget
        kind: EC2NodeClass
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["c","m","r"]
        - key: karpenter.k8s.aws/instance-size
          operator: NotIn
          values: ["nano","micro","small","medium"]
        - key: karpenter.k8s.aws/instance-hypervisor
          operator: In
          values: ["nitro"]
      expireAfter: 720h
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m
    budgets:
    - nodes: "0"
      schedule: "0 0 * * *"
      duration: 24h
---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: disruption-budget
spec:
  amiSelectorTerms: 
  - alias: bottlerocket@latest
  role: "<<KARPENTER_NODE_IAM_ROLE_NAME>>"
  securityGroupSelectorTerms:
  - tags:
      karpenter.sh/discovery: <<CLUSTER_NAME>>
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: <<CLUSTER_NAME>>