apiVersion: apps/v1
kind: Deployment
metadata:
  name: disruption-budget
spec:
  replicas: 30
  selector:
    matchLabels:
      intent: disruption-budget
  template:
    metadata:
      labels:
        intent: disruption-budget
    spec:
      nodeSelector:
        intent: disruption-budget
      containers:
      - name: disruption-budget
        image: public.ecr.aws/eks-distro/kubernetes/pause:3.7
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 512m
            memory: 512Mi 
      topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              intent: disruption-budget
          maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
        - labelSelector:
            matchLabels:
              intent: disruption-budget
          maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway