apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-multi-az-nodes
spec:
  replicas: 30
  selector:
    matchLabels:
      app: workload-multi-az-nodes
  template:
    metadata:
      labels:
        app: workload-multi-az-nodes
    spec:
      nodeSelector:
        intent: apps
      containers:
      - name: workload-multi-az-nodes
        image: public.ecr.aws/eks-distro/kubernetes/pause:3.7
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 512m
            memory: 512Mi 
      topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              app: workload-multi-az-nodes
          maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
        - labelSelector:
            matchLabels:
              app: workload-multi-az-nodes
          maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway